version: '3.8'
services:
  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./code:/usr/share/nginx/html
    ports:
      - "9000"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lab7_rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
  nginx:
    image: nginx:alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./code:/var/www/html
    depends_on:
      - php
    networks:
    - lab7_network
networks:
  lab7_network:
    driver: bridge